// Singleton loader for RDKit.js (cheminformatics) and 3Dmol.js (WebGL viewer)
// Both are loaded from CDN so the bundle stays slim.

declare global {
  interface Window {
    initRDKitModule?: (opts?: { locateFile?: (f: string) => string }) => Promise<RDKitModule>;
    RDKit?: RDKitModule;
    $3Dmol?: any;
  }
}

export interface RDKitMol {
  is_valid(): boolean;
  add_hs(): void;
  get_molblock(): string;
  get_mol_copy(): RDKitMol;
  get_smiles(): string;
  delete(): void;
}

export interface RDKitModule {
  get_mol(smiles: string, details?: string): RDKitMol;
  version?(): string;
}

const RDKIT_VERSION = '2024.3.5';
const RDKIT_BASE = `https://unpkg.com/@rdkit/rdkit@${RDKIT_VERSION}/dist`;
const TDMOL_URL = 'https://3dmol.org/build/3Dmol-min.js';

let rdkitPromise: Promise<RDKitModule> | null = null;
let tdmolPromise: Promise<any> | null = null;

function loadScript(src: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const existing = document.querySelector(`script[src="${src}"]`);
    if (existing) {
      if ((existing as any)._loaded) return resolve();
      existing.addEventListener('load', () => resolve());
      existing.addEventListener('error', () => reject(new Error(`Failed to load ${src}`)));
      return;
    }
    const s = document.createElement('script');
    s.src = src;
    s.async = true;
    s.onload = () => {
      (s as any)._loaded = true;
      resolve();
    };
    s.onerror = () => reject(new Error(`Failed to load ${src}`));
    document.head.appendChild(s);
  });
}

export function loadRDKit(): Promise<RDKitModule> {
  if (typeof window === 'undefined') return Promise.reject(new Error('RDKit needs window'));
  if (window.RDKit) return Promise.resolve(window.RDKit);
  if (rdkitPromise) return rdkitPromise;

  rdkitPromise = loadScript(`${RDKIT_BASE}/RDKit_minimal.js`)
    .then(() => {
      if (!window.initRDKitModule) throw new Error('initRDKitModule not found');
      return window.initRDKitModule({
        locateFile: (file: string) => `${RDKIT_BASE}/${file}`,
      });
    })
    .then((mod) => {
      window.RDKit = mod;
      return mod;
    })
    .catch((e) => {
      rdkitPromise = null;
      throw e;
    });

  return rdkitPromise;
}

export function load3Dmol(): Promise<any> {
  if (typeof window === 'undefined') return Promise.reject(new Error('3Dmol needs window'));
  if (window.$3Dmol) return Promise.resolve(window.$3Dmol);
  if (tdmolPromise) return tdmolPromise;

  tdmolPromise = loadScript(TDMOL_URL)
    .then(() => {
      if (!window.$3Dmol) throw new Error('$3Dmol not found after load');
      return window.$3Dmol;
    })
    .catch((e) => {
      tdmolPromise = null;
      throw e;
    });

  return tdmolPromise;
}

/**
 * Convert a SMILES string into a 3D MOL block (V2000) with hydrogens added
 * and ETKDG/MMFF coordinates generated by RDKit.
 * Returns null if SMILES is invalid.
 */
export async function smilesTo3DMolBlock(smiles: string): Promise<string | null> {
  const rdkit = await loadRDKit();
  const mol = rdkit.get_mol(smiles, JSON.stringify({ removeHs: false }));
  if (!mol || !mol.is_valid()) {
    mol?.delete();
    return null;
  }
  try {
    // Try to generate 3D coordinates. RDKit-JS exposes get_molblock with
    // embed parameters via JSON details. We pass coordgen+addCoords flags.
    // Fallback: 2D molblock if 3D fails.
    let molblock: string;
    try {
      // Newer RDKit-JS supports 3D embedding through get_new_coords / generate_3d_coords
      const anyMol = mol as any;
      if (typeof anyMol.generate_aligned_coords === 'function') {
        // ignore - aligned needs ref
      }
      if (typeof anyMol.add_hs === 'function') anyMol.add_hs();
      if (typeof anyMol.set_new_coords === 'function') {
        anyMol.set_new_coords(true); // true => 3D
      } else if (typeof anyMol.generate_3d_coords === 'function') {
        anyMol.generate_3d_coords();
      }
      molblock = mol.get_molblock();
    } catch {
      molblock = mol.get_molblock();
    }
    return molblock;
  } finally {
    mol.delete();
  }
}
